version: '3.3'
services:
  loquiapi:
    image: sc-registry.fredhutch.org/loquiapi:latest
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.loquiapi.rule=Host(`loquiapi.fredhutch.org`)"
        - "traefik.http.routers.loquiapi-secured.rule=Host(`loquiapi.fredhutch.org`)"
        - "traefik.http.routers.loquiapi.entrypoints=web,web-secured"
        - "traefik.http.services.loquiapi.loadbalancer.server.port=9876" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.loquiapi.tls=true"

networks:
  proxy:
    external: true
