# Candace Savonen Feb 2024

name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-build:
    name: Run checks
    runs-on: ubuntu-latest
    container:
      image: fredhutch/loquiapi:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_PAT}}
          fetch-depth: 0

      - name: Run the tests
        run: |
          install.packages("devtools")
          devtools::test()
        shell: Rscript {0}

      - name: Check testthat results
        id: check_check
        run: |
          error_num=$(Rscript --vanilla '.github/workflows/check_testthat.R')
          echo "error_num=$error_num" >> $GITHUB_OUTPUT

      - name: Stop if there are errors!
        if: ${{ steps.check_check.outputs.error_num != '0' }}
        run: exit 1

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name:
          path: check
